-- Generated by tools/import_emoji.py - do not edit by hand.
-- Noto emoji v2.047 packed into /main/assets/emoji/sheet.png;
-- see MANIFEST.json there for which glyph sits in which cell.
return {
	barrow = { u0 = 0.007812, v0 = 0.757812, u1 = 0.242188, v1 = 0.992188 },
	city = { u0 = 0.257812, v0 = 0.757812, u1 = 0.492188, v1 = 0.992188 },
	gems = { u0 = 0.507812, v0 = 0.757812, u1 = 0.742188, v1 = 0.992188 },
	mine = { u0 = 0.757812, v0 = 0.757812, u1 = 0.992188, v1 = 0.992188 },
	portal = { u0 = 0.007812, v0 = 0.507812, u1 = 0.242188, v1 = 0.742188 },
	ruins = { u0 = 0.257812, v0 = 0.507812, u1 = 0.492188, v1 = 0.742188 },
	seat = { u0 = 0.507812, v0 = 0.507812, u1 = 0.742188, v1 = 0.742188 },
	shrine = { u0 = 0.757812, v0 = 0.507812, u1 = 0.992188, v1 = 0.742188 },
}
