-- Generated by tools/import_emoji.py - do not edit by hand.
-- Noto emoji v2.047 exported one glyph apiece into /main/emoji.atlas,
-- for GUI scenes; the map's own glyphs live in main/emoji_sheet.lua.
return {
	bombard = "emoji_bombard",
	escort = "emoji_escort",
	interceptor = "emoji_interceptor",
}
