-- Generated by tools/import_emoji.py - do not edit by hand.
-- Noto emoji v2.047 exported one glyph apiece into /main/emoji.atlas.
-- Covers both vocabularies: M.EMOJI (map sprites) and M.UNIT_EMOJI (GUI).
return {
	barrow = "emoji_barrow",
	bombard = "emoji_bombard",
	capital = "emoji_capital",
	colony = "emoji_colony",
	escort = "emoji_escort",
	gems = "emoji_gems",
	interceptor = "emoji_interceptor",
	mine = "emoji_mine",
	portal = "emoji_portal",
	ruins = "emoji_ruins",
	shrine = "emoji_shrine",
}
