--- Which emoji a system is drawn as.
--
-- The map is drawn in Google Noto color emoji, and the vocabulary is
-- **semantic**: the glyph says what a place is for, not what it looks like
-- through a telescope. A castle is a capital, a cityscape is somewhere people
-- live, a pick or a satellite dish is why an outpost is worth holding, and a
-- bare sparkle is terrain.
--
-- One resolver, shared by the game (`main/galaxy.script`), the offline sketch
-- (`tools/render_map.py` regex-parses `M.EMOJI` for codepoints) and the tests
-- (`tools/test_wire.lua` checks every name this can produce exists in the
-- sheet). It sits on `galaxy.sim.systems.profile`, which both a locally
-- generated galaxy and a server-decoded one satisfy - so the wire and the
-- fallback cannot disagree about what a system is drawn as.
--
-- `M.EMOJI` maps a *name* to a Noto codepoint. The names are this module's
-- contract with `main/emoji_sheet.lua` (generated by `tools/import_emoji.py`);
-- the codepoints are its contract with the Noto assets. Spare glyphs are
-- packed but unmapped so retuning a muddy assignment is a one-line edit here,
-- with no re-import.

local systems = require("galaxy.sim.systems")

local M = {}

-- name -> Noto emoji codepoint (png/512/emoji_uXXXX.png in googlefonts/noto-emoji)
M.EMOJI = {
	capital = "1f3f0",    -- castle
	colony = "1f3d9",     -- cityscape
	asteroids = "26cf",   -- pick
	derelict = "2699",    -- gear
	relay = "1f6f0",      -- satellite
	ruins = "1f3db",      -- classical building
	nebula = "1f300",     -- cyclone
	-- A solid star, not 💫: anything swooshy-yellow drowns among the waypoint
	-- sparkles, which the first sketch proved within one render.
	energetic = "2b50",   -- star: anomalies, pulsars, blue giants
	black_hole = "1f573", -- hole
	waypoint = "2728",    -- sparkles
	-- Spares, packed but unmapped:
	dizzy = "1f4ab",      -- dizzy
	houses = "1f3d8",     -- houses
	factory = "1f3ed",    -- factory
	saucer = "1f6f8",     -- flying saucer
}

-- An outpost is drawn as the thing that makes it one. Feature first, then
-- class - the same precedence `systems.profile` uses to decide it is an
-- outpost at all.
local FEATURE_EMOJI = {
	asteroids = "asteroids",
	derelict = "derelict",
	relay = "relay",
	ruins = "ruins",
	nebula = "nebula",
	anomaly = "energetic",
}

local CLASS_EMOJI = {
	nebula = "nebula",
	black_hole = "black_hole",
	pulsar = "energetic",
	blue_giant = "energetic",
}

--- The sheet name for a system. `is_capital` is game state, not map data, so
-- the caller supplies it; browsing a bare seed never draws a castle.
function M.emoji_for(galaxy, id, is_capital)
	if is_capital then return "capital" end
	local kind = systems.kind(galaxy, id)
	if kind == systems.COLONY then return "colony" end
	if kind == systems.WAYPOINT then return "waypoint" end
	local star = galaxy.stars[id]
	return FEATURE_EMOJI[star.feature]
		or CLASS_EMOJI[star.class]
		or "energetic"
end

return M
