--- What a tile is drawn as: the ground under it, and the glyph on top.
--
-- This module resolves the two semantic art layers. The political influence
-- outline between them is state-dependent and is selected by main/realm.script
-- through realm/influence.lua instead.
--
--   the ground   a hand-drawn hex from /main/tiles.atlas, chosen by the tile's
--                terrain and biome. What the land *is*.
--   the glyph    a Google Noto emoji from /main/emoji.atlas, drawn over the
--                hex. What is *on* the land - a castle, a village, a mine.
--
-- The glyph vocabulary is **semantic**: it says what a place is for, not what it
-- would look like from the air. And it is deliberately sparse - open country
-- gets no glyph at all, because the hex underneath already says it is forest.
-- The old map drew a sparkle on every wilds only because a bare disc said
-- nothing.
--
-- One resolver, shared by the game (`main/realm.script`), the offline sketch
-- (`tools/render_map.py`) and the tests (`tools/test_wire.lua` checks every name
-- this can produce exists in the atlas). It sits on `realm.sim.tiles.profile`
-- and the tile's own terrain, which both a locally generated map and a
-- server-decoded one satisfy - so the wire and the offline fallback cannot
-- disagree about what a tile is drawn as.

local tiles = require("realm.sim.tiles")

local M = {}

-- The *ground*, drawn as a hex sprite underneath everything else.
--
-- `M.TILES` maps a terrain name to the `foundation_tiles` pack's own file
-- suffix. The names on the left are this module's contract with
-- `realm.terrain`; the suffixes on the right are its contract with the art,
-- and are why `plains` can be drawn with a tile the artist called "tundra"
-- without either side having to lie. tools/import_tiles.py parses this.
--
-- Deliberately only the *ground* types. The pack also draws villages, cities,
-- keeps, ruins and crystals as tiles, and none of them are imported: those are
-- places, `M.EMOJI` below already draws them, and a drawn city inside the hex
-- under an emoji city on top of it is two cities.
M.TILES = {
	water     = "water",     -- sea. Not in the graph at all - see realm/land.lua
	plains    = "tundra",    -- default open ground
	forest    = "forest",
	woods     = "trees",     -- sparser forest
	hills     = "hills",
	mountains = "mountains",
}

-- The five ground palettes the pack ships. Same art, same alpha mask, different
-- ground colour - so a biome is a colour rather than a redraw, and every terrain
-- above exists in every one of these. Order matches realm.terrain's M.BIOMES.
M.BIOMES = { "greenlands", "sandlands", "drylands", "deadlands", "icelands" }

-- The art's own pixel dimensions. The sprite scale is derived from these -
-- a tile is drawn `2 * hex_size` world units wide, so its scale is
-- `2 * hex_size / TILE_PX.w` - and both importers assert against them, so
-- swapping in a differently-sized pack fails the import rather than silently
-- rescaling the whole map.
--
-- 238 x 207 is not arbitrary: it is exactly the bounding box of a flat-top
-- hexagon of size 119 (2s by sqrt(3)*s = 238 x 206.1, rounded up a pixel), which
-- is what lets plain sprite quads tessellate. tools/test_hex.lua proves it.
M.TILE_PX = { w = 238, h = 207 }
M.GLYPH_PX = 224

-- The *interface* vocabulary is exported smaller than the map's, because it is
-- drawn smaller: a unit sits in a 62-unit slot, which is ~124 physical pixels on
-- a 2x phone, while a map glyph is a sprite scaled to the hex and can fill the
-- screen at the closest zoom. One size for both meant paying 224px for art
-- nothing ever draws above 128 - and with six themes' worth of units that is the
-- difference between one atlas page and two.
M.UI_PX = 128

-- How much of a tile's width a glyph covers. A glyph has to read as sitting *on*
-- the hex rather than covering it - the hex's own art is what says the ground is
-- forest, and a glyph big enough to hide it would be saying it twice.
-- tools/render_map.py mirrors these, so a size approved in the sketch transfers.
M.GLYPH_SCALE = { city = 0.46, holding = 0.40 }
M.SEAT_GLYPH_SCALE = 0.56

-- One palette for the whole sea, rather than each stretch of water taking its
-- neighbour's. A coastline that changes colour along its length reads as a
-- rendering fault rather than as geography.
M.SEA_BIOME = "icelands"

-- name -> Noto emoji codepoint (png/512/emoji_uXXXX.png in googlefonts/noto-emoji).
-- The names are this module's contract with `main/emoji_ui.lua` (generated by
-- tools/import_emoji.py); the codepoints are its contract with the Noto assets.
M.EMOJI = {
	-- Places people hold.
	seat = "1f3f0",    -- castle: a player's seat
	city  = "1f3d8",    -- houses: somewhere people live

	-- Features. Each of these is exactly why a tile nobody could live on is
	-- still worth marching to, which is why every one of them is drawn.
	ruins   = "1f3db",    -- classical building
	mine    = "26cf",     -- pick
	shrine  = "26e9",     -- shinto shrine
	barrow  = "1faa6",    -- headstone
	portal  = "1f300",    -- cyclone
	gems    = "1f48e",    -- gem stone
}

-- Interface glyphs, drawn by GUI scenes rather than by the map's sprites.
--
-- Still a separate table, but no longer for a separate *mechanism*: both
-- vocabularies now land in /main/emoji.atlas as named images, because a sprite
-- can no more be handed a UV rect than a GUI node can. It is kept apart because
-- it is keyed by `realm.sim.units` id rather than by map meaning, so the
-- mapping is exhaustive by construction and `tools/test_wire.lua` can prove it.
M.UNIT_EMOJI = {
	-- The fallback, used for a race that declares no art of its own. Deliberately
	-- plain: these are the shapes the three *roles* have, before a theme puts a
	-- cow or a drake in the slot.
	escort      = "1f6e1", -- shield: takes the hits so the rest do not
	interceptor = "2694",  -- crossed swords: hunts what is standing there
	bombard     = "1f4a3", -- bomb: breaks defences

	-- terran
	terran_escort            = "1f404",  -- ox: plods forward and takes it
	terran_interceptor       = "1f415",  -- hound: runs down what runs
	terran_bombard           = "1f417",  -- boar: goes through the gate

	-- vorn
	vorn_escort              = "1f6e1",  -- shield: the wall that walks
	vorn_interceptor         = "1f40e",  -- horse: rides past the line
	vorn_bombard             = "1f528",  -- hammer: breaks the wall

	-- ashai
	ashai_escort             = "2620",   -- bones: already dead, hard to kill again
	ashai_interceptor        = "1f987",  -- bat: a swarm nobody can hold
	ashai_bombard            = "1f383",  -- gourd: rots the stone

	-- kepler
	kepler_escort            = "1f9ff",  -- ward: turns the blow aside
	kepler_interceptor       = "1f9da",  -- sprite: gets behind them
	kepler_bombard           = "1f409",  -- drake: burns the gate down

	-- cartel
	cartel_escort            = "2693",   -- anchor: holds the ground
	cartel_interceptor       = "1f99c",  -- parrot: the ship that catches you
	cartel_bombard           = "1f4a3",  -- bomb: opens the hull

	-- silicate
	silicate_escort          = "1faa8",  -- stone: does not move
	silicate_interceptor     = "1f410",  -- goat: over ground nobody else crosses
	silicate_bombard         = "1f4a5",  -- blast: takes the mountain out
}

-- A feature is drawn as itself. One entry per productive feature in
-- `realm.terrain`, and `tools/test_wire.lua` fails if one is missing - an
-- holding with no glyph would be a tile the player cannot tell from open ground
-- while it quietly counts towards somebody's victory.
local FEATURE_EMOJI = {
	ruins  = "ruins",
	mine   = "mine",
	shrine = "shrine",
	barrow = "barrow",
	portal = "portal",
	gems   = "gems",
}

--- The atlas image for a tile's ground.
function M.tile_for(realm, id)
	local tile = realm.tiles[id]
	return "tile_" .. tile.biome .. "_" .. tile.terrain
end

--- The atlas image for a stretch of sea.
function M.sea_tile()
	return "tile_" .. M.SEA_BIOME .. "_water"
end

--- The glyph name for a tile, or **nil for open country**.
--
-- `is_seat` is game state rather than map data, so the caller gold it;
-- browsing a bare seed never draws a castle.
function M.emoji_for(realm, id, is_seat)
	if is_seat then return "seat" end
	local kind = tiles.kind(realm, id)
	if kind == tiles.CITY then return "city" end
	if kind == tiles.WILDS then return nil end
	return FEATURE_EMOJI[realm.tiles[id].feature]
end


-- The faces an officer can wear, eight per theme.
--
-- **A portrait is a role, not a medium.** These fill exactly the ids
-- `realm/sim/commanders.lua` already names - `portrait_<race>_NN` - so nothing
-- in the simulation, the wire or `ui.portrait` had to learn that the art
-- changed. What changed is where it comes from: seventy-two pieces of art whose
-- licence was never established, for Noto under Apache 2.0.
--
-- Eight rather than twelve because a player raises at most four officers
-- (`rules.commander_cap_max`), and eight readably different emoji per theme is
-- achievable where twelve is not - past that a cast is one person eight times,
-- which is the failure the old importer's MIN_SPACING existed to avoid.
--
-- Order is load-bearing: an officer's face is its *number* modulo the cast, so
-- the nth officer a player raises always has both the same name and the same
-- face. Reordering a theme silently reassigns every existing commander's face.
M.FACE_EMOJI = {
	-- **The first four of each cast are the ones that must not look alike.** A
	-- face is an officer's number modulo the cast and a player may raise four,
	-- so slots 01-04 are the only ones ever on screen together in the commander
	-- strip. Those are picked for silhouette - a hat, a helmet, a colour - and
	-- the near-twins every family of emoji contains are parked at 05-08, where
	-- they are only ever reached after the index has wrapped.

	-- terran: Freeholders
	terran_01      = "1f9d1_200d_1f33e",  -- straw hat
	terran_02      = "1f920",             -- cowboy hat
	terran_03      = "1f9d1_200d_1f373",  -- cook's toque
	terran_04      = "1f9d3",             -- grey
	terran_05      = "1f469_200d_1f33e",  -- farmer
	terran_06      = "1f468_200d_1f33e",  -- farmer
	terran_07      = "1f475",             -- grandmother
	terran_08      = "1f9d4",             -- beard

	-- vorn: Iron Order
	vorn_01        = "1f934",             -- crown
	vorn_02        = "1f482",             -- busby
	vorn_03        = "1f93a",             -- fencer, in white
	vorn_04        = "1f977",             -- ninja, in black
	vorn_05        = "1f478",             -- crown
	vorn_06        = "1fac5",             -- crown
	vorn_07        = "1f473",             -- turban
	vorn_08        = "1f3c7",             -- mounted

	-- ashai: The Barrow
	ashai_01       = "1f9df",             -- green revenant
	ashai_02       = "1f9db",             -- red collar
	ashai_03       = "1f47b",             -- white ghost
	ashai_04       = "1f479",             -- red oni
	ashai_05       = "1f9df_200d_2640",   -- revenant
	ashai_06       = "1f9db_200d_2640",   -- revenant
	ashai_07       = "1f47a",             -- tengu
	ashai_08       = "1f480",             -- bare skull

	-- kepler: The Circle
	kepler_01      = "1f9d9",             -- blue hat
	kepler_02      = "1f9dd",             -- elf
	kepler_03      = "1f9de",             -- blue genie
	kepler_04      = "1f9dc",             -- merfolk
	kepler_05      = "1f9d9_200d_2640",   -- mage
	kepler_06      = "1f9dd_200d_2640",   -- elf
	kepler_07      = "1f9d1_200d_1f393",  -- mortarboard
	kepler_08      = "1f9cc",             -- troll

	-- cartel: Free Company
	cartel_01      = "1f9b9",             -- purple
	cartel_02      = "1f9d1_200d_2708",   -- captain's cap
	cartel_03      = "1f575",             -- detective's hat
	cartel_04      = "1f978",             -- an obvious disguise
	cartel_05      = "1f9b9_200d_2640",   -- purple
	cartel_06      = "1f935",             -- black tie
	cartel_07      = "1f9d1_200d_1f3a4",  -- loud
	cartel_08      = "1f412",             -- the ship's monkey

	-- silicate: Stonekin
	silicate_01    = "1f5ff",             -- carved head
	silicate_02    = "1f477",             -- hard hat
	silicate_03    = "1f916",             -- made, not born
	silicate_04    = "1f9d1_200d_1f3ed",  -- the works
	silicate_05    = "1f9d1_200d_1f527",  -- spanner
	silicate_06    = "1f9d1_200d_1f52c",  -- glass and reagents
	silicate_07    = "1f468_200d_1f3ed",  -- the works
	silicate_08    = "1f469_200d_1f3ed",  -- the works
}

-- What a theme calls the three unit types.
--
-- Nested, unlike the codepoint tables above, because `tools/import_emoji.py`
-- never reads this one - only the tables it has to fetch art for must stay flat
-- for its regex. See `theme_table()` there.
--
-- A pair is `{ singular, plural }`; the plural is omitted wherever "s" is right,
-- which is everywhere but the ox. `ui.plural_word` already takes both, because
-- the order bar counts a mix out as "2 Oxen, 1 Boar".
--
-- **The ids, costs and powers underneath are untouched.** A theme is art and
-- names, never numbers: the moment one changes a cost the sweep's medians stop
-- describing the game.
M.UNIT_NAME = {
	terran = {
		escort       = { "Ox", "Oxen" },
		interceptor  = { "Hound" },
		bombard      = { "Boar" },
	},
	vorn = {
		escort       = { "Shield" },
		interceptor  = { "Rider" },
		bombard      = { "Ram" },
	},
	ashai = {
		escort       = { "Skeleton" },
		interceptor  = { "Bat" },
		bombard      = { "Blight" },
	},
	kepler = {
		escort       = { "Ward" },
		interceptor  = { "Sprite" },
		bombard      = { "Drake" },
	},
	cartel = {
		escort       = { "Anchor" },
		interceptor  = { "Corsair" },
		bombard      = { "Keg" },
	},
	silicate = {
		escort       = { "Boulder" },
		interceptor  = { "Goat" },
		bombard      = { "Blast" },
	},
}

-- What a theme calls the five buildings. Names only - a building draws one of
-- the interface kit's icons rather than a glyph of its own (`BUILDING_ICON` in
-- `main/hud.gui_script`), so this costs no art.
--
-- The blurb is *derived* rather than listed: a dwelling's is "<what it makes>,
-- ready to buy.", built from M.UNIT_NAME above. A second table would be the
-- place the Barn goes on saying "Escorts" after the Ox was renamed.
M.BUILDING_NAME = {
	terran = {
		berths           = "Barn",
		interceptor_bay  = "Kennel",
		foundry          = "Sty",
		bastion          = "Stockade",
		admiralty        = "Moot Hall",
	},
	vorn = {
		berths           = "Barracks",
		interceptor_bay  = "Stables",
		foundry          = "Smithy",
		bastion          = "Keep",
		admiralty        = "Great Hall",
	},
	ashai = {
		berths           = "Crypt",
		interceptor_bay  = "Roost",
		foundry          = "Blight Pit",
		bastion          = "Bone Wall",
		admiralty        = "Ossuary",
	},
	kepler = {
		berths           = "Sanctum",
		interceptor_bay  = "Grove",
		foundry          = "Hatchery",
		bastion          = "Wardstone",
		admiralty        = "Conclave",
	},
	cartel = {
		berths           = "Shipwright",
		interceptor_bay  = "Crow's Nest",
		foundry          = "Powder House",
		bastion          = "Sea Fort",
		admiralty        = "Captain's Table",
	},
	silicate = {
		berths           = "Quarry",
		interceptor_bay  = "Pasture",
		foundry          = "Delve",
		bastion          = "Rampart",
		admiralty        = "Deep Hall",
	},
}

local function themed(source, race, key)
	local by_race = race and source[race]
	return by_race and by_race[key] or nil
end

--- The M.UNIT_EMOJI name for a unit type as *this* theme draws it.
--
-- Falls back to the bare unit id, which is always in the table, so a race added
-- to `realm/sim/races.lua` without art draws the plain role rather than an empty
-- circle where the player's army should be. `tools/test_wire.lua` is what stops
-- that fallback going unnoticed.
function M.unit_emoji(race, id)
	local name = race and (race .. "_" .. id)
	if name and M.UNIT_EMOJI[name] then return name end
	return id
end

--- A unit type's name in this theme, singular and plural.
--
-- `spec` is the wire record (`view.units[i]`) or a catalogue entry - anything
-- carrying `id` and `name` - so the caller never needs a second lookup to find
-- the fallback.
function M.unit_name(race, spec)
	local id = (type(spec) == "table") and spec.id or spec
	local entry = themed(M.UNIT_NAME, race, id)
	if entry then return entry[1], entry[2] or (entry[1] .. "s") end
	local plain = ((type(spec) == "table") and spec.name) or id
	return plain, plain .. "s"
end

--- A building's name and blurb in this theme.
--
-- `spec` is the wire record (`view.buildings[i]`): `id`, `name`, `blurb`, and
-- `makes` for the three that arm somebody. The blurb follows the unit name so
-- the two cannot drift; a building that makes nothing keeps the catalogue's own,
-- which is already theme-neutral ("Harder to take. Arms nobody.").
function M.building_name(race, spec)
	local id = (type(spec) == "table") and spec.id or spec
	local name = themed(M.BUILDING_NAME, race, id)
		or ((type(spec) == "table") and spec.name) or id
	local blurb = (type(spec) == "table") and spec.blurb or nil
	local makes = (type(spec) == "table") and spec.makes or nil
	local entry = makes and themed(M.UNIT_NAME, race, makes)
	if entry then
		blurb = (entry[2] or (entry[1] .. "s")) .. ", ready to buy."
	end
	return name, blurb
end


return M
