--- What a tile is drawn as: the ground under it, and the glyph on top.
--
-- Two layers, two mechanisms, and this module is the one resolver for both.
--
--   the ground   a hand-drawn hex from /main/tiles.atlas, chosen by the tile's
--                terrain and biome. What the land *is*.
--   the glyph    a Google Noto emoji from /main/emoji.atlas, drawn over the
--                hex. What is *on* the land - a castle, a village, a mine.
--
-- The glyph vocabulary is **semantic**: it says what a place is for, not what it
-- would look like from the air. And it is deliberately sparse - open country
-- gets no glyph at all, because the hex underneath already says it is forest.
-- The old map drew a sparkle on every waypoint only because a bare disc said
-- nothing.
--
-- One resolver, shared by the game (`main/galaxy.script`), the offline sketch
-- (`tools/render_map.py`) and the tests (`tools/test_wire.lua` checks every name
-- this can produce exists in the atlas). It sits on `galaxy.sim.systems.profile`
-- and the tile's own terrain, which both a locally generated map and a
-- server-decoded one satisfy - so the wire and the offline fallback cannot
-- disagree about what a tile is drawn as.

local systems = require("galaxy.sim.systems")

local M = {}

-- The *ground*, drawn as a hex sprite underneath everything else.
--
-- `M.TILES` maps a terrain name to the `foundation_tiles` pack's own file
-- suffix. The names on the left are this module's contract with
-- `galaxy.terrain`; the suffixes on the right are its contract with the art,
-- and are why `plains` can be drawn with a tile the artist called "tundra"
-- without either side having to lie. tools/import_tiles.py parses this.
--
-- Deliberately only the *ground* types. The pack also draws villages, cities,
-- keeps, ruins and crystals as tiles, and none of them are imported: those are
-- places, `M.EMOJI` below already draws them, and a drawn city inside the hex
-- under an emoji city on top of it is two cities.
M.TILES = {
	water     = "water",     -- sea. Not in the graph at all - see galaxy/land.lua
	plains    = "tundra",    -- default open ground
	forest    = "forest",
	woods     = "trees",     -- sparser forest
	hills     = "hills",
	mountains = "mountains",
}

-- The five ground palettes the pack ships. Same art, same alpha mask, different
-- ground colour - so a biome is a colour rather than a redraw, and every terrain
-- above exists in every one of these. Order matches galaxy.terrain's M.BIOMES.
M.BIOMES = { "greenlands", "sandlands", "drylands", "deadlands", "icelands" }

-- The art's own pixel dimensions. The sprite scale is derived from these -
-- a tile is drawn `2 * hex_size` world units wide, so its scale is
-- `2 * hex_size / TILE_PX.w` - and both importers assert against them, so
-- swapping in a differently-sized pack fails the import rather than silently
-- rescaling the whole map.
--
-- 238 x 207 is not arbitrary: it is exactly the bounding box of a flat-top
-- hexagon of size 119 (2s by sqrt(3)*s = 238 x 206.1, rounded up a pixel), which
-- is what lets plain sprite quads tessellate. tools/test_hex.lua proves it.
M.TILE_PX = { w = 238, h = 207 }
M.GLYPH_PX = 224

-- How much of a tile's width a glyph covers. A glyph has to read as sitting *on*
-- the hex rather than covering it - the hex's own art is what says the ground is
-- forest, and a glyph big enough to hide it would be saying it twice.
-- tools/render_map.py mirrors these, so a size approved in the sketch transfers.
M.GLYPH_SCALE = { colony = 0.46, outpost = 0.40 }
M.CAPITAL_GLYPH_SCALE = 0.56

-- One palette for the whole sea, rather than each stretch of water taking its
-- neighbour's. A coastline that changes colour along its length reads as a
-- rendering fault rather than as geography.
M.SEA_BIOME = "icelands"

-- name -> Noto emoji codepoint (png/512/emoji_uXXXX.png in googlefonts/noto-emoji).
-- The names are this module's contract with `main/emoji_ui.lua` (generated by
-- tools/import_emoji.py); the codepoints are its contract with the Noto assets.
M.EMOJI = {
	-- Places people hold.
	capital = "1f3f0",    -- castle: a player's seat
	colony  = "1f3d8",    -- houses: somewhere people live

	-- Features. Each of these is exactly why a tile nobody could live on is
	-- still worth marching to, which is why every one of them is drawn.
	ruins   = "1f3db",    -- classical building
	mine    = "26cf",     -- pick
	shrine  = "26e9",     -- shinto shrine
	barrow  = "1faa6",    -- headstone
	portal  = "1f300",    -- cyclone
	gems    = "1f48e",    -- gem stone
}

-- Interface glyphs, drawn by GUI scenes rather than by the map's sprites.
--
-- Still a separate table, but no longer for a separate *mechanism*: both
-- vocabularies now land in /main/emoji.atlas as named images, because a sprite
-- can no more be handed a UV rect than a GUI node can. It is kept apart because
-- it is keyed by `galaxy.sim.units` id rather than by map meaning, so the
-- mapping is exhaustive by construction and `tools/test_wire.lua` can prove it.
M.UNIT_EMOJI = {
	escort      = "1f6e1", -- shield: takes the hits so the rest do not
	interceptor = "1f680", -- rocket: hunts ships
	bombard     = "1f4a3", -- bomb: breaks defences
}

-- A feature is drawn as itself. One entry per productive feature in
-- `galaxy.terrain`, and `tools/test_wire.lua` fails if one is missing - an
-- outpost with no glyph would be a tile the player cannot tell from open ground
-- while it quietly counts towards somebody's victory.
local FEATURE_EMOJI = {
	ruins  = "ruins",
	mine   = "mine",
	shrine = "shrine",
	barrow = "barrow",
	portal = "portal",
	gems   = "gems",
}

--- The atlas image for a tile's ground.
function M.tile_for(galaxy, id)
	local star = galaxy.stars[id]
	return "tile_" .. star.biome .. "_" .. star.terrain
end

--- The atlas image for a stretch of sea.
function M.sea_tile()
	return "tile_" .. M.SEA_BIOME .. "_water"
end

--- The glyph name for a tile, or **nil for open country**.
--
-- `is_capital` is game state rather than map data, so the caller supplies it;
-- browsing a bare seed never draws a castle.
function M.emoji_for(galaxy, id, is_capital)
	if is_capital then return "capital" end
	local kind = systems.kind(galaxy, id)
	if kind == systems.COLONY then return "colony" end
	if kind == systems.WAYPOINT then return nil end
	return FEATURE_EMOJI[galaxy.stars[id].feature]
end

return M
