#!/usr/bin/env python3
"""Import the map's emoji glyphs from Google Noto emoji.

Like import_portraits.py, this is an import of third-party art rather than a
regeneration step - the output is Noto's drawings, not something derived from
parameters here - so alongside the sheet it records provenance: which glyphs,
from which release, packed into which cells (MANIFEST.json), under what terms
(NotoEmoji-LICENSE.txt, CREDITS.txt).

The glyph list is not declared here: it is parsed out of `main/theme.lua`'s
M.EMOJI table, which is the single source of truth for what the map can draw.
Run this after changing that table. It writes:

    main/assets/emoji/sheet.png           4x4 grid of 256px cells, 1024x1024
    main/assets/emoji/MANIFEST.json       provenance + cell assignments
    main/assets/emoji/CREDITS.txt         attribution
    main/assets/emoji/NotoEmoji-LICENSE.txt
    main/emoji_sheet.lua                  name -> UV rect (generated, never
                                          hand-edited - like main/ui.atlas)

Glyphs are downscaled 512 -> 224 (LANCZOS) and centred, leaving a 16px
transparent gutter per cell; the UV rects are inset a further 8px so linear
sampling and mip generation never bleed a neighbouring glyph into an edge.
The sheet is straight alpha - Defold premultiplies at build time, the same
contract as every other texture in the project.
"""
import io
import json
import os
import re
import sys
import urllib.request

from PIL import Image

NOTO_REF = "v2.047"
NOTO_URL = "https://raw.githubusercontent.com/googlefonts/noto-emoji/%s/png/512/emoji_u%s.png"
LICENSE_URL = "https://raw.githubusercontent.com/googlefonts/noto-emoji/%s/LICENSE"

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
THEME = os.path.join(ROOT, "main", "theme.lua")
OUT_DIR = os.path.join(ROOT, "main", "assets", "emoji")
SHEET = os.path.join(OUT_DIR, "sheet.png")
UV_MODULE = os.path.join(ROOT, "main", "emoji_sheet.lua")
CACHE = os.path.join(ROOT, "build", "emoji_cache")

GRID = 4          # cells per side
CELL = 256        # px per cell
GLYPH = 224       # glyph size inside the cell (16px gutter each side)
INSET = 8         # UV inset from the cell edge, px
SHEET_PX = GRID * CELL

# Defold flips PNGs to GL convention at build time, so v=0 is the bottom of
# the image. If the first engine build shows the castle upside down, this is
# the one switch to flip.
FLIP_V = True


def theme_emoji():
    """name -> codepoint, parsed from main/theme.lua's M.EMOJI block."""
    src = open(THEME).read()
    block = re.search(r"M\.EMOJI\s*=\s*\{(.*?)\n\}", src, re.S)
    if not block:
        sys.exit("import_emoji: no M.EMOJI block found in main/theme.lua")
    pairs = re.findall(r'(\w+)\s*=\s*"([0-9a-f_]+)"', block.group(1))
    if not pairs:
        sys.exit("import_emoji: M.EMOJI block parsed empty")
    return dict(pairs)


def fetch(url, path):
    if os.path.exists(path):
        return open(path, "rb").read()
    print("fetch %s" % url)
    with urllib.request.urlopen(url) as r:
        if r.status != 200:
            sys.exit("import_emoji: %d for %s" % (r.status, url))
        data = r.read()
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as f:
        f.write(data)
    return data


def main():
    emoji = theme_emoji()
    names = sorted(emoji)
    if len(names) > GRID * GRID:
        sys.exit("import_emoji: %d glyphs do not fit a %dx%d sheet"
                 % (len(names), GRID, GRID))

    sheet = Image.new("RGBA", (SHEET_PX, SHEET_PX), (0, 0, 0, 0))
    manifest_cells = {}
    for i, name in enumerate(names):
        cp = emoji[name]
        raw = fetch(NOTO_URL % (NOTO_REF, cp),
                    os.path.join(CACHE, "emoji_u%s.png" % cp))
        img = Image.open(io.BytesIO(raw)).convert("RGBA")
        img = img.resize((GLYPH, GLYPH), Image.LANCZOS)
        col, row = i % GRID, i // GRID
        pad = (CELL - GLYPH) // 2
        sheet.paste(img, (col * CELL + pad, row * CELL + pad))
        manifest_cells[name] = {"codepoint": cp, "cell": i}

    os.makedirs(OUT_DIR, exist_ok=True)
    sheet.save(SHEET)
    print("sheet.png %dx%d, %d glyphs" % (SHEET_PX, SHEET_PX, len(names)))

    # UV rects, inset from the cell so sampling never reaches a neighbour.
    # v0 is the glyph's bottom edge and v1 its top, matching how
    # build_stars hands corners to meshbuild's quad().
    lines = [
        "-- Generated by tools/import_emoji.py - do not edit by hand.",
        "-- Noto emoji %s packed into /main/assets/emoji/sheet.png;" % NOTO_REF,
        "-- see MANIFEST.json there for which glyph sits in which cell.",
        "return {",
    ]
    for i, name in enumerate(names):
        col, row = i % GRID, i // GRID
        x0 = (col * CELL + INSET) / SHEET_PX
        x1 = ((col + 1) * CELL - INSET) / SHEET_PX
        yt = (row * CELL + INSET) / SHEET_PX          # top edge, image space
        yb = ((row + 1) * CELL - INSET) / SHEET_PX    # bottom edge, image space
        if FLIP_V:
            v0, v1 = 1.0 - yb, 1.0 - yt
        else:
            v0, v1 = yb, yt
        lines.append("\t%s = { u0 = %.6f, v0 = %.6f, u1 = %.6f, v1 = %.6f },"
                     % (name, x0, v0, x1, v1))
    lines.append("}")
    with open(UV_MODULE, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("main/emoji_sheet.lua: %d entries" % len(names))

    license_text = fetch(LICENSE_URL % NOTO_REF,
                         os.path.join(CACHE, "LICENSE-%s" % NOTO_REF)).decode()
    with open(os.path.join(OUT_DIR, "NotoEmoji-LICENSE.txt"), "w") as f:
        f.write("Copyright 2013 Google LLC (https://github.com/googlefonts/noto-emoji)\n\n"
                "The Noto emoji artwork in this directory is licensed under the\n"
                "Apache License, Version 2.0. The license is copied below, and is\n"
                "also available at http://www.apache.org/licenses/LICENSE-2.0\n\n\n")
        f.write(license_text)

    with open(os.path.join(OUT_DIR, "CREDITS.txt"), "w") as f:
        f.write("""Map emoji
=========

Google Noto color emoji, from the googlefonts/noto-emoji repository at tag
%s. The 512px PNGs were downscaled to %dpx, centred in %dpx cells and packed
into sheet.png by tools/import_emoji.py; the artwork itself is unmodified.
Which glyphs the map uses is decided by main/theme.lua, and MANIFEST.json
here records exactly which codepoint landed in which cell.

LICENCE: Apache License, Version 2.0 - see NotoEmoji-LICENSE.txt beside this
file. Re-running the importer after editing main/theme.lua regenerates the
sheet and main/emoji_sheet.lua together, so the mapping and the art cannot
drift apart.
""" % (NOTO_REF, GLYPH, CELL))

    with open(os.path.join(OUT_DIR, "MANIFEST.json"), "w") as f:
        json.dump({"ref": NOTO_REF, "grid": GRID, "cell": CELL, "glyph": GLYPH,
                   "uv_inset": INSET, "flip_v": FLIP_V, "glyphs": manifest_cells},
                  f, indent=1, sort_keys=True)
        f.write("\n")
    print("MANIFEST.json, CREDITS.txt, NotoEmoji-LICENSE.txt written")


if __name__ == "__main__":
    main()
